### ISSUE TITLE
Input parameters not parsed properly

### ISSUE THREAD

**Issue by dshore** [ksindi/monoreaper#4]
https://tldp.org/LDP/abs/html/quotingvar.html:
> When referencing a variable, it is generally advisable to enclose its name in double quotes. This prevents reinterpretation of all special characters within the quoted string -- except $, ` (backquote), and \ (escape). 

This is not being pared correctly:
https://github.com/ksindi/monoreaper/blob/master/monoreaper.sh#L65

Snippet of error:
```
#!/bin/bash
for repo in "${@:1}"
do
    IFS="/" read owner repo_name repo_branch <<<$repo
    echo "owner=$owner"
    echo "repo_name=$repo_name"
done
```
Errantly returns this because $repo is reinterpreted:
```
owner=owner0 repo0
repo_name=
owner=owner1 repo1
repo_name=
```

I believe it should be this, notice quotes:
```
IFS="/" read owner repo_name repo_branch <<<"$repo"
```

**Comment by dshore** [comment]
@ksindi We love this at JW Player.  Thx for the continued support!

**Comment by ksindi** [comment]
@dshore thank you for finding my bugs ;-)

**Comment by ksindi** [comment]
@dshore I have added the quotes
